package sg.com.jp.generalcargo.domain;

//package: ejb.sessionBeans.cab.billing;


import java.rmi.RemoteException;

/**
 * 
 * @author swho
 * Created Jan 18, 2002 4:40:16 PM
 * Code generated by the Forte for Java EJB Module
 */

public interface BillErrorHome{
    public BillError create() throws RemoteException;
}

