package sg.com.jp.generalcargo.domain;

//package: ejb.sessionBeans.cab.billing;

import java.rmi.RemoteException;
import java.sql.SQLException;

/**
 * 
 * @author swho Created Jan 18, 2002 4:40:16 PM Code generated by the Forte for
 *         Java EJB Module
 */

public interface BillError {
	public void insertBillError(BillErrorVO billErrorValueObject) throws RemoteException, SQLException;
}
