package sg.com.jp.generalcargo.domain;

import java.io.Serializable;
import java.sql.Timestamp;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * 
 * @author swho Created Nov 11, 2001 3:40:35 PM Code generated by the Forte for
 *         Java EJB Module
 */

public final class CntrEventLogKey implements Serializable {
	private static final long serialVersionUID = 1L;
	public Integer cntrSeqNbr;
	public Timestamp txnDttm;
	public String txnCd;

	public CntrEventLogKey() {
	}

	public Integer getCntrSeqNbr() {
		return cntrSeqNbr;
	}

	public void setCntrSeqNbr(Integer cntrSeqNbr) {
		this.cntrSeqNbr = cntrSeqNbr;
	}

	public Timestamp getTxnDttm() {
		return txnDttm;
	}

	public void setTxnDttm(Timestamp txnDttm) {
		this.txnDttm = txnDttm;
	}

	public String getTxnCd() {
		return txnCd;
	}

	public void setTxnCd(String txnCd) {
		this.txnCd = txnCd;
	}

	@Override
	public String toString() {
		try {
			return new ObjectMapper().writeValueAsString(this);
		} catch (JsonProcessingException e) {
			return "";
		}
	}

}
